"""Observability evidence builders for paper-readiness validation."""

from ta_model.observability.paper_readiness import (
    METRIC_DATA_BLOCKED_COUNT,
    METRIC_DATA_STALE_COUNT,
    METRIC_EXECUTION_COST_PREDICTION_ERROR_ABS,
    METRIC_EXECUTION_ORDER_REJECT_COUNT,
    METRIC_EXECUTION_TCA_ERROR_COUNT,
    METRIC_MODEL_CALIBRATION_ERROR,
    METRIC_MODEL_VALIDATION_BLOCKER_COUNT,
    METRIC_PORTFOLIO_ACCOUNT_STATE_LINKAGE_GAP,
    METRIC_PORTFOLIO_MAX_DRAWDOWN_PCT,
    METRIC_PORTFOLIO_TOTAL_EXECUTION_COST,
    METRIC_RISK_HARD_BREACH_COUNT,
    METRIC_RISK_KILL_SWITCH_BLOCK_COUNT,
    METRIC_RISK_PRE_TRADE_BLOCK_COUNT,
    METRIC_STRATEGY_COST_DRAG_NOTIONAL,
    METRIC_STRATEGY_NO_TRADE_QUALITY_DELTA,
    PaperReadinessConfigError,
    build_paper_readiness_observability_report,
    load_paper_readiness_alert_rules,
    load_paper_readiness_dashboard_spec,
    make_default_paper_readiness_alert_rules,
    make_default_paper_readiness_dashboard_spec,
    make_paper_readiness_alert_rules_from_config,
    make_paper_readiness_dashboard_spec_from_config,
)

__all__ = [
    "METRIC_DATA_BLOCKED_COUNT",
    "METRIC_DATA_STALE_COUNT",
    "METRIC_EXECUTION_COST_PREDICTION_ERROR_ABS",
    "METRIC_EXECUTION_ORDER_REJECT_COUNT",
    "METRIC_EXECUTION_TCA_ERROR_COUNT",
    "METRIC_MODEL_CALIBRATION_ERROR",
    "METRIC_MODEL_VALIDATION_BLOCKER_COUNT",
    "METRIC_PORTFOLIO_ACCOUNT_STATE_LINKAGE_GAP",
    "METRIC_PORTFOLIO_MAX_DRAWDOWN_PCT",
    "METRIC_PORTFOLIO_TOTAL_EXECUTION_COST",
    "METRIC_RISK_HARD_BREACH_COUNT",
    "METRIC_RISK_KILL_SWITCH_BLOCK_COUNT",
    "METRIC_RISK_PRE_TRADE_BLOCK_COUNT",
    "METRIC_STRATEGY_COST_DRAG_NOTIONAL",
    "METRIC_STRATEGY_NO_TRADE_QUALITY_DELTA",
    "PaperReadinessConfigError",
    "build_paper_readiness_observability_report",
    "load_paper_readiness_alert_rules",
    "load_paper_readiness_dashboard_spec",
    "make_default_paper_readiness_alert_rules",
    "make_default_paper_readiness_dashboard_spec",
    "make_paper_readiness_alert_rules_from_config",
    "make_paper_readiness_dashboard_spec_from_config",
]
